// Customer
export const CUSTOMER_ACTION_DATA = 'CUSTOMER_ACTION_DATA';
export const CUSTOMER_ACTION_ERROR = 'CUSTOMER_ACTION_ERROR';
export const CUSTOMER_ACTION_FETCH = 'CUSTOMER_ACTION_FETCH';
export const CUSTOMER_ACTION_RESET = 'CUSTOMER_ACTION_RESET';

export const CUSTOMER_CREATE_DATA = 'CUSTOMER_CREATE_DATA';
export const CUSTOMER_CREATE_ERROR = 'CUSTOMER_CREATE_ERROR';
export const CUSTOMER_CREATE_FETCH = 'CUSTOMER_CREATE_FETCH';
export const CUSTOMER_CREATE_RESET = 'CUSTOMER_CREATE_RESET';

export const CUSTOMER_DELETE_DATA = 'CUSTOMER_DELETE_DATA';
export const CUSTOMER_DELETE_ERROR = 'CUSTOMER_DELETE_ERROR';
export const CUSTOMER_DELETE_FETCH = 'CUSTOMER_DELETE_FETCH';
export const CUSTOMER_DELETE_RESET = 'CUSTOMER_DELETE_RESET';

export const CUSTOMER_DETAIL_DATA = 'CUSTOMER_DETAIL_DATA';
export const CUSTOMER_DETAIL_ERROR = 'CUSTOMER_DETAIL_ERROR';
export const CUSTOMER_DETAIL_FETCH = 'CUSTOMER_DETAIL_FETCH';
export const CUSTOMER_DETAIL_RESET = 'CUSTOMER_DETAIL_RESET';

export const CUSTOMER_LIST_DATA = 'CUSTOMER_LIST_DATA';
export const CUSTOMER_LIST_ERROR = 'CUSTOMER_LIST_ERROR';
export const CUSTOMER_LIST_FETCH = 'CUSTOMER_LIST_FETCH';
export const CUSTOMER_LIST_RESET = 'CUSTOMER_LIST_RESET';

export const CUSTOMER_UPDATE_DATA = 'CUSTOMER_UPDATE_DATA';
export const CUSTOMER_UPDATE_ERROR = 'CUSTOMER_UPDATE_ERROR';
export const CUSTOMER_UPDATE_FETCH = 'CUSTOMER_UPDATE_FETCH';
export const CUSTOMER_UPDATE_RESET = 'CUSTOMER_UPDATE_RESET';
