// dummies
export const DUMMY_ACTION_DATA = 'DUMMY_ACTION_DATA';
export const DUMMY_ACTION_ERROR = 'DUMMY_ACTION_ERROR';
export const DUMMY_ACTION_FETCH = 'DUMMY_ACTION_FETCH';
export const DUMMY_ACTION_RESET = 'DUMMY_ACTION_RESET';

export const DUMMY_CREATE_DATA = 'DUMMY_CREATE_DATA';
export const DUMMY_CREATE_ERROR = 'DUMMY_CREATE_ERROR';
export const DUMMY_CREATE_FETCH = 'DUMMY_CREATE_FETCH';
export const DUMMY_CREATE_RESET = 'DUMMY_CREATE_RESET';

export const DUMMY_DELETE_DATA = 'DUMMY_DELETE_DATA';
export const DUMMY_DELETE_ERROR = 'DUMMY_DELETE_ERROR';
export const DUMMY_DELETE_FETCH = 'DUMMY_DELETE_FETCH';
export const DUMMY_DELETE_RESET = 'DUMMY_DELETE_RESET';

export const DUMMY_DETAIL_DATA = 'DUMMY_DETAIL_DATA';
export const DUMMY_DETAIL_ERROR = 'DUMMY_DETAIL_ERROR';
export const DUMMY_DETAIL_FETCH = 'DUMMY_DETAIL_FETCH';
export const DUMMY_DETAIL_RESET = 'DUMMY_DETAIL_RESET';

export const DUMMY_LIST_DATA = 'DUMMY_LIST_DATA';
export const DUMMY_LIST_ERROR = 'DUMMY_LIST_ERROR';
export const DUMMY_LIST_FETCH = 'DUMMY_LIST_FETCH';
export const DUMMY_LIST_RESET = 'DUMMY_LIST_RESET';

export const DUMMY_UPDATE_DATA = 'DUMMY_UPDATE_DATA';
export const DUMMY_UPDATE_ERROR = 'DUMMY_UPDATE_ERROR';
export const DUMMY_UPDATE_FETCH = 'DUMMY_UPDATE_FETCH';
export const DUMMY_UPDATE_RESET = 'DUMMY_UPDATE_RESET';
